dist: xenial
language: bash

services:
  - docker

matrix:
  include:
    - env: flavour=latest BUILD_TAG=jakzal/phpqa:travis-php7.1-latest PHP_VERSION=7.1
    - env: flavour=alpine BUILD_TAG=jakzal/phpqa:travis-php7.1-alpine PHP_VERSION=7.1
    - env: flavour=latest BUILD_TAG=jakzal/phpqa:travis-php7.2-latest PHP_VERSION=7.2
    - env: flavour=alpine BUILD_TAG=jakzal/phpqa:travis-php7.2-alpine PHP_VERSION=7.2
    - env: flavour=latest BUILD_TAG=jakzal/phpqa:travis-php7.3-latest PHP_VERSION=7.3 BUILD_NIGHTLY=true UPDATE_TOOLBOX=true
    - env: flavour=alpine BUILD_TAG=jakzal/phpqa:travis-php7.3-alpine PHP_VERSION=7.3 BUILD_NIGHTLY=true TRIGGER_DOCKER_HUB=true
  fast_finish: true

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - git config user.email 'jakub@zalas.pl' && git config user.name 'Jakub Zalas'

script:
  - make build-$flavour
  - docker run -it --rm $BUILD_TAG php -v | grep 'PHP '$PHP_VERSION
  - docker run -it --rm $BUILD_TAG php /tools/toolbox test
  - docker run -it --rm $BUILD_TAG

after_script:
  - docker images

after_success:
  - |
    test "$TRAVIS_EVENT_TYPE" == "cron" && test "$TRIGGER_DOCKER_HUB" == "true" && \
      curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/jakzal/phpqa/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
  - test "$TRAVIS_EVENT_TYPE" == "cron" && test "$BUILD_NIGHTLY" == "true" && make build-nightly-$flavour
  - test "$TRAVIS_EVENT_TYPE" == "cron" && test "$UPDATE_TOOLBOX" == "true" && make update-toolbox-pr

env:
  global:
    - secure: "cMMMnYD944bDunA9wwOIhxTg9xJPK+y+8Tac7+D4e+nww23AFsVfT1RhWypB67Y0FUBRbNyxc73yZIFm00pF/jFNpY8ZYxLacjnARqU5m6JZXNiNxr8KMhPm2O4cggoIV5SOqXylPirNvFpWIqiXxkfE/K/aoPHDRWRCsl2Qq2VqcDya6/AexrGlGsD7BLxTb9HNoOcvhWwsAusg8VTNfRVMor53PIKC69ALcLAi2XBniOVJ9hYOo24sCsG0t9CRl6H1Ch0EdgQWYSMGtGLsKcrMa+lqL/W7tGTJkubNkIhA+/iqO0qIwSEyEKvV0LJjI7Pgq19+yRtG9x1gt0fuzRPSklU4rYdNy07KRlGK59WMp7h2BXIUetHpisfBwWK91JptUUe0Vfu+n4E9n026bA+Vk8ZfZIYdh2brXCWnLriZO5WHg+DL2to/6O60YwxoL/aP6STl84+Lv4SUip36hi38NFaFFIMrwT4bWlPAgsGRYGzZ3Itwn1R1FfzwkNaU7lKFNmlQRRF+egsAM65K102y/dDF+x74/DtV6esBw4SjoGI3q8uSBXBqc/kJRJEHaZIbmMJEoyNj1s81lwwnHKhVPQo9eTn3Ayzi+P5WxS8XuEHhPScGhfiIrWnVcw6tIyy8P5uAyfsfyVlL3hCsPwRae4vmSaV98Du3Nv51Cgc="
    - secure: "ddd+1gMQ/ll8o3MZ8g8HQl7RsawJHETzUq7rncNQbJRc29vZmDfOcDworCsjJUmOQ9rIADxcylFlU1HXuEjkh9nmE78o8YMI44fJPHIGbYvuw6wvlPYR/GEqdmAhy8EE94eZQMLROhBFqj8J70H2Prpy/06+YvijtPipbEjNd3w2RVLjiyYj1BBC5i5psIXbX/OHfFsKDOHQv5ZIWeRvdeTW951bOPdEbCbOWKwz4cz4xvggJAMVlclbqdHqNFz2YWDAhyglGgwXt6dapRQuYskT4kXfht+CDIhulIdiEgRDaKM6PzKS7Irxv7P18VCtFbsbwf7LGDMbnvio5mOPRp2nk6VK5wdiBUyKQGAR6cuc2X3dpDJsu/zImJspqhLeYYeYcUSDQu6Z2QYZMk5my7A3VHsc9h5DFKwkGBDsD7Y8AfxDAbNah3+B9hNM0t+MaoQDou0vrcGrjtG6pMKEE6X3Ilpe6IebtAbby3RGIZjpU04OqnY8Tv1hCmQ+gEN/6eLJxqjEwHp6KZ7VGhH8ceMlpXJ+qhW1zGqcU5TNrO4ljb8ibIO+PsYDTuXR8YhVzm050yeKb4vtPkeFNBmDesKKGlK9JFb3aeRxGy9O7dx5Hxgq51rZlwuFtccOb8shYwMmk7lWCPTY5WehN6iYVVTA6Ky989aWPlmuK/pOUdw="
    - secure: "m9Q8Ekvm6LWkRRUmuSBZiVfgcwt/YFQCwRgzDEvMRR1LHFirgdAPZw18m5pFXr9YzkA3TGP3mUzqE3UAAjof7hDbBkUbiZL/6ynLRIWKj3EyWmViYdmVAQSNh26UBagL9m8ZLmRBvAfpD9My8XY/XSFYMnMQSeLqdpYbWE0GF9+aCJ1hlGpavycSrw4rjarLuvzHgWFNSFX13FQBYFMmBGJjkWi8xiT1yKCS6sMjH3JfenVfcDUlzTorR68463eHeZ1sUtZFGPXak9LczEcZpc8FhZIoWdJ+33QTzhh3qOXHWmcpxVMyF24I8JYn8N3PSlEx39jCaKkdPcoYL1jMaGyDwnftAFrtyYNANU7R+Bp5r8HQ2F1qEkLNIlEKZtxSQA4dTXtwkB5cNktaX5srhL7wdkhj01tGhyA+P5cy5UXGk2zUYFW8Yrk3kxjh0+FJC9pHtVlObFMJJqD8SVQCO1Z+CyZ+wv2MH5BhhQstQnZY3pBSwoSHgqTNvjioUjOwBUGy50mOvUGjtEzo/k1Svzxcw521SNACqfBwYhVlc8VP/3gPxZ+UwZNsnQpTfVDHxhaAhfTTG69g+LP4oSP0OxUlpGffzQdl1/GLqXAANRpgfDKQxzY/PMhkkwhQwhzfXbbpTeq70MbvhgQmUjUyFDKo8uETgNmP5MiyIVxoQSI="

addons:
  snaps:
  - name: hub
    classic: true
  - name: jq
    classic: true
