language: bash
sudo: required

services:
  - docker

matrix:
  include:
    - env: flavour=latest BUILD_TAG=jakzal/phpqa:travis-7.1-latest PHP_VERSION=7.1
    - env: flavour=alpine BUILD_TAG=jakzal/phpqa:travis-7.1-alpine PHP_VERSION=7.1
    - env: flavour=latest BUILD_TAG=jakzal/phpqa:travis-7.2-latest PHP_VERSION=7.2
    - env: flavour=alpine BUILD_TAG=jakzal/phpqa:travis-7.2-alpine PHP_VERSION=7.2
  fast_finish: true

script:
  - make build-$flavour
  - docker run -it --rm $BUILD_TAG php /usr/local/bin/tools.php test
  - docker run -it --rm $BUILD_TAG

after_script:
  - docker images
  - docker run -it --rm $BUILD_TAG sh -c '(php /usr/local/bin/tools.php update-phars && diff $TOOLS_JSON.bak $TOOLS_JSON) || echo -e "\033[0;91mSome tools might have new phar releases. Update tools.json.\033[0m"'

after_success:
  - |
    if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/jakzal/phpqa/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
      make build-nightly-$flavour
    fi

env:
  global:
    - secure: "iO9RzZwdZiq/txA3qaKrcEgGePvBaIEQd9Znh4JMNlynunJ21ewgqzFKYlDejEqdc3Q9KCwDSlfXSaJ1mNPWxyEjBcdVWNe/IRj5+5U/bbczio4mKZ7dfw/ocCjlpeSkmCyPF3CwKmcybzWk9wQiWZkXrGdwdfzdwWgfmDb/gKzrDO3LQtEalnSiqAu8E7aE5Mwrul+0zn1IqHU3zu46GPYfs7hOpgNXg7v3L/GT8L/WGbTzRwDN0miNewxiY61J4U9ktyTeOk4mX01+lACTZuJCQe9ZKX2MatY8Bs+O9RxQSK2EAAZ4Pi25Yim9g/ry+FaV4a6K+4u/zvQKwZLjW96Hm8+/1gGfYecPOXzw7FUEEow+xzY5jyAuQpGATrXRiay7sT1bQlS6Ga7t2KATS0ifgatzDGK3LRFzlcXJkO2lD5z3uH7M5ft9eVUkVtr51BtP5Q7vwv26uq/+0/NS+9vVZe9XzK1Ew4SpdU3Z0Y7mJH4PrOTkjIOC+8j1Xu+FcqVynEzsUn1l3Bka+Y0bICekU6QrzFn1PfhRBypZHy/k0gndhXBvGXAU9qA4QscMDwdSMAjMDC/i1D/qOk5KeGHoG6/CtocMLXXB+k8MCLA0LX6uHRMEqUgIUyEKX+14luFBeMbfUCOF1cXozqOOVZnm4pgSJMddl3+AvRaQIq0="
    - secure: "ddd+1gMQ/ll8o3MZ8g8HQl7RsawJHETzUq7rncNQbJRc29vZmDfOcDworCsjJUmOQ9rIADxcylFlU1HXuEjkh9nmE78o8YMI44fJPHIGbYvuw6wvlPYR/GEqdmAhy8EE94eZQMLROhBFqj8J70H2Prpy/06+YvijtPipbEjNd3w2RVLjiyYj1BBC5i5psIXbX/OHfFsKDOHQv5ZIWeRvdeTW951bOPdEbCbOWKwz4cz4xvggJAMVlclbqdHqNFz2YWDAhyglGgwXt6dapRQuYskT4kXfht+CDIhulIdiEgRDaKM6PzKS7Irxv7P18VCtFbsbwf7LGDMbnvio5mOPRp2nk6VK5wdiBUyKQGAR6cuc2X3dpDJsu/zImJspqhLeYYeYcUSDQu6Z2QYZMk5my7A3VHsc9h5DFKwkGBDsD7Y8AfxDAbNah3+B9hNM0t+MaoQDou0vrcGrjtG6pMKEE6X3Ilpe6IebtAbby3RGIZjpU04OqnY8Tv1hCmQ+gEN/6eLJxqjEwHp6KZ7VGhH8ceMlpXJ+qhW1zGqcU5TNrO4ljb8ibIO+PsYDTuXR8YhVzm050yeKb4vtPkeFNBmDesKKGlK9JFb3aeRxGy9O7dx5Hxgq51rZlwuFtccOb8shYwMmk7lWCPTY5WehN6iYVVTA6Ky989aWPlmuK/pOUdw="
